spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/lote
spring.datasource.username=master
spring.datasource.password=p34c3m4k3r
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true