spring.application.name=backend
spring.datasource.url=jdbc:postgresql://postgres:5432/lotes_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.sql.init.mode=always
spring.jackson.serialization.fail-on-empty-beans=false